# openapi.yaml (Corrected based on provided URLs)
swagger: '2.0'
info:
  title: ColorLock API
  version: 1.0.0
schemes:
  - https
produces:
  - application/json

# Define Firebase Authentication Security
securityDefinitions:
  firebase_auth:
    type: oauth2
    flow: implicit
    authorizationUrl: "" # Required but not used for implicit flow
    x-google-issuer: "https://securetoken.google.com/color-lock-prod"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "color-lock-prod"

# NOTE: Removed top-level x-google-backend. Backend is defined per-path now.

paths:
  /fetchPuzzle: # Path exposed by the API Gateway
    options:
      summary: CORS support for fetchPuzzle
      operationId: corsFetchPuzzle
      responses:
        '204':
          description: CORS Preflight Check Successful
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type, Authorization, X-Emulator-User-Id'
            Access-Control-Max-Age:
              type: string
              default: '3600'
    post:
      summary: Fetches the daily puzzle
      operationId: fetchPuzzle
      security:
        - firebase_auth: []
      x-google-backend:
        # Address of the SPECIFIC backend function URL
        address: "https://us-central1-color-lock-prod.cloudfunctions.net/fetchPuzzle"
        # Audience for the token the GATEWAY generates to call the BACKEND
        jwt_audience: "https://us-central1-color-lock-prod.cloudfunctions.net/fetchPuzzle"
        # Use CONSTANT_ADDRESS because the backend URL already includes the function path
        path_translation: CONSTANT_ADDRESS
      responses:
        '200':
          description: Successful response with puzzle data
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '400':
          description: Bad Request (e.g., missing date)
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '401':
          description: Unauthorized (Invalid Firebase Token)
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '403':
          description: Forbidden (Origin issue or other)
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '404':
          description: Puzzle not found
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '500':
          description: Internal Server Error
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'

  /updateUserStats: # Path exposed by the API Gateway
    options:
      summary: CORS support for updateUserStats
      operationId: corsUpdateUserStats
      responses:
        '204':
          description: CORS Preflight Check Successful
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type, Authorization, X-Emulator-User-Id'
            Access-Control-Max-Age:
              type: string
              default: '3600'
    post:
      summary: Updates user statistics
      operationId: updateUserStats
      security:
        - firebase_auth: []
      x-google-backend:
        address: "https://us-central1-color-lock-prod.cloudfunctions.net/updateUserStatsHttp"
        jwt_audience: "https://us-central1-color-lock-prod.cloudfunctions.net/updateUserStatsHttp"
        path_translation: CONSTANT_ADDRESS
      responses:
        '200':
          description: Stats updated successfully
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '400':
          description: Bad Request
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '401':
          description: Unauthorized
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '403':
          description: Forbidden
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '500':
          description: Internal Server Error
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'

  /getDailyScoresStats: # Path exposed by the API Gateway
    options:
      summary: CORS support for getDailyScoresStats
      operationId: corsGetDailyScoresStats
      responses:
        '204':
          description: CORS Preflight Check Successful
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type, Authorization, X-Emulator-User-Id'
            Access-Control-Max-Age:
              type: string
              default: '3600'
    post:
      summary: Gets daily score statistics
      operationId: getDailyScoresStats
      security:
        - firebase_auth: []
      x-google-backend:
        # Update to point to the HTTP version of the function
        address: "https://us-central1-color-lock-prod.cloudfunctions.net/getDailyScoresStatsHttp"
        # Update JWT audience to match the HTTP function URL
        jwt_audience: "https://us-central1-color-lock-prod.cloudfunctions.net/getDailyScoresStatsHttp"
        path_translation: CONSTANT_ADDRESS
      responses:
        '200':
          description: Stats retrieved successfully
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '400':
          description: Bad Request
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '401':
          description: Unauthorized
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '403':
          description: Forbidden
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '500':
          description: Internal Server Error
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'

  /getUserStats: # Path exposed by the API Gateway
    options:
      summary: CORS support for getUserStats
      operationId: corsGetUserStats
      responses:
        '204':
          description: CORS Preflight Check Successful
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type, Authorization, X-Emulator-User-Id'
            Access-Control-Max-Age:
              type: string
              default: '3600'
    post:
      summary: Gets user statistics
      operationId: getUserStats
      security:
        - firebase_auth: []
      x-google-backend:
        address: "https://us-central1-color-lock-prod.cloudfunctions.net/getUserStatsHttp"
        jwt_audience: "https://us-central1-color-lock-prod.cloudfunctions.net/getUserStatsHttp"
        path_translation: CONSTANT_ADDRESS
      responses:
        '200':
          description: User stats retrieved successfully
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '400':
          description: Bad Request
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '401':
          description: Unauthorized
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '403':
          description: Forbidden
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'
        '500':
          description: Internal Server Error
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://colorlock.xyz'